# This workflow is going to be used during the development phase of the project
# The workflow builds and tests the the sources on the following triggers:
#   - once a change is pushed to the main branch or any of its sub-branches
name: Library development workflow

on:
  push:
    branches:
      - 'main'  # runs the workflow, once new changes have been integrated to main
      - 'main/**' # runs the workflow, once new changes have been integrated to a sub-branch of main
  pull_request:
    branches:
      - 'main' # run workflow in the scope of pull requests towards main
  workflow_call:
    secrets:
      APAX_TOKEN:
        required: true
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read     # required for checkout
  packages: read     # required for pulling the SIMATIC AX container

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # either check out a provided reference, or use the reference that triggered the workflow call, e.g. a push, PR or a release
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: 'yes'
          base-branch: 'main'